config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  resources :questions, only: [:index, :update, :new, :edit, :create, :destroy]
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :templates, only: [:new, :create, :index, :show, :destroy] # Order matters!
  resources :template_questions, only: [:create, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :template_questions
  has_many :templates, through: :template_questions, dependent: :destroy # To remove question from many-many table after deleting a questions that was in templates
  validates :ask, presence: true, length: {minimum: 3, maximum: 100}
end

app/models/template.rb
class Template < ApplicationRecord
  has_many :template_questions
  has_many :questions, through: :template_questions
  validates :name, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
end

app/models/template_question.rb
class TemplateQuestion < ApplicationRecord
  belongs_to :template
  belongs_to :question
  validates_uniqueness_of :question_id, :scope => :template_id
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :questions, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def new
    @question = Question.new
  end

  def index
    @questions = Question.all
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "Question was saved successfully." # For flash display. Common flash keys: notice, alert
      redirect_to questions_path
    else
      render 'new'
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    flash[:notice] = "Question was successfully deleted."
    redirect_to questions_path
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:id, :ask, :answer, template_ids: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    # user = User.find_by(email: params[:session][:email].downcase)
    user = User.find_by(username: params[:session][:username])
    if (user)
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to root_path
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/template_questions_controller.rb
class TemplateQuestionsController < ApplicationController

  def new
    @template_question = TemplateQuestion.new
  end

  def create
    @template_question = TemplateQuestion.new(template_question_params)
    @template_question.save
  end

  private

  def template_question_params
    params.require(:template_question).permit(:question_id, :template_id)
  end

end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:show, :edit, :update, :destroy]

  def index
    @templates = Template.all
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
          render pdf: "Template No. #{@template.id}",
          page_size: 'A4',
          template: "templates/_document.html.erb",
          layout: "pdf.html",
          orientation: "Portrait",
          lowquality: true,
          zoom: 1,
          dpi: 75
      end
  end
  end

  def new
    @template = Template.new
  end

  def create
    @template = Template.new(template_params)
    if @template.save
      flash[:notice] = "Template was saved successfully."
      redirect_to templates_path
    else
      render 'new'
    end
  end

  def destroy
    @template.destroy
    flash[:notice] = "Template was successfully deleted."
    redirect_to templates_path
  end

  private

  def set_template
    @template = Template.find(params[:id])
  end

  def template_params
    params.require(:template).permit(:id, :name, question_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Mini Dealmaker #{@user.username}, you have successfully signed up"
      redirect_to questions_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small><%= link_to "Dealmaker", "https://dealmaker.tech", class: "text-white" %> &copy; 2021 </small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <% if name == "notice" %>
      <% msg_type = "success" %>
    <% else %>
      <% msg_type = "danger" %>
    <% end %>
    <div class="alert alert-<%= msg_type %> alert-dismissible fade show role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <%= link_to "DEALMAKER", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon bg-light"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Questions
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "View questions", questions_path, class: "dropdown-item" %></li>
            <% if logged_in? %>
              <li><%= link_to "Create new question", new_question_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Templates
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "View templates", templates_path, class: "dropdown-item" %></li>
            <% if logged_in? %>
              <li><%= link_to "Create new template", new_template_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item">
            <a class="nav-link" aria-expanded="false">
              Username: [<%= current_user.username %>]
            </a>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniDealmaker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Template PDF</title>
    <%= wicked_pdf_stylesheet_link_tag "template" %>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Welcome to Mini Dealmaker!</h1>
    <p class="lead">This is my solution to the Dealmaker coding challenge.</p>
    <hr class="my-4">
    <p>Please take a look aruond the website and let me know what you think.</p>
    <%= link_to 'Sign up!', signup_path, class: "btn btn-lg", id: "home-button"%>
  </div>
</div>

app/views/questions/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'layouts/errors', obj: @question %>
      <%= form_with(model: @question, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="input-group row mb-3">
          <%= f.label :ask, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :ask, class: "form-control shadow rounded", placeholder: "Fill in question here" %>
          </div>
        </div>

        <div class="input-group row mb-3">
          <%= f.label :answer, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :answer, rows: 10, class: "form-control shadow rounded", placeholder: "Fill in answer here" %>
          </div>
        </div>

        <div class="input-group justify-content-center mb-3">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <%= link_to '[Cancel and return to questions listing]', questions_path, class: "text-primary text-center mb-3" %>
  </div>
</div>

app/views/questions/index.html.erb
<%= javascript_pack_tag 'questionTable' %>

<div id='questionTable'></div>

app/views/questions/new.html.erb
<h1 class="text-center mt-4">Create a new question</h1>
<%= render 'form' %>

app/views/templates/_document.html.erb
<div class="container mt-4 mb-4">
  <div class="invoice-box">
    <table cellpadding="0" cellspacing="0">
      <tr class="top">
        <td colspan="4">
          <table>
            <tr>
              <td class="title">
                <%= image_tag wicked_pdf_asset_base64('dealmaker-logo.png'), width: "70%", height: "auto"%>
              </td>

              <td>
                Template No. #: <b><%= @template.id %></b>
                <br>
                Created: <b><%= @template.created_at.strftime('%d/%m/%Y') %></b>
                <br>
                Last Updated: <b><%= (@template.updated_at).strftime('%d/%m/%Y') %></b>
                <br>
                Status: <span class="badge rounded-pill bg-primary me-1 text-decoration-none">Open</span>
              </td>
            </tr>
          </table>
        </td>
      </tr>

      <tr class="information">
        <td colspan="4">
          <table>
            <tr>
              <td>
                <b><%= @template.name %></b><br>
                <i class="bi bi-building"></i> Placeholder for company address<br>
                <i class="bi bi-envelope-fill"></i> Company Email placeholder<br>
                <i class="bi bi-telephone-fill"></i> Company Phone placeholder
              </td>

              <td>
                <b>Potential Investor Name</b><br>
                <i class="bi bi-building"></i> Placeholder for investor address<br>
                <i class="bi bi-envelope-fill"></i> Investor Email placeholder<br>
                <i class="bi bi-telephone-fill"></i> Investor Phone placeholder
              </td>
            </tr>
          </table>
        </td>
      </tr>

      <% if @template.questions.count > 0 %>

        <tr class="heading">
          <td>Question</td>
          <td class="">Answer</td>
          <td colspan="2"></td>

        </tr>

        <% @template.questions.each do |question| %>
          <tr class="item">
            <td>
              <%= question.ask %><br>
            </td>

            <td class="right">
              <%= question.answer %>
            </td>
          </tr>
        <% end %>
      <% else %>

        <tr class="heading">
          <td><i>This is currently a blank template</i></td>
        </tr>

        <tr class="item">
          <td>
            <p style="color:grey"><i>Questions and answers will appear here as you assign them to this template. To create questions and assign them to templates, go to the Questions tab dropdown in the navigation bar.</i></p>
          </td>
        </tr>
      <% end %>

      <tr>
        <td colspan="2"></td>
      </tr>

      <tr class="heading">
        <td class="text-center"><b>Dealmaker &copy; 2021</b></td>
      </tr>
    </table>
  </div>
</div>

app/views/templates/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'layouts/errors', obj: @template %>
      <%= form_with(model: @template, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="input-group row mb-3">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Please enter a template name" %>
          </div>
        </div>

        <div class="input-group justify-content-center mb-3">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <%= link_to '[Cancel and return to templates listing]', templates_path, class: "text-primary text-center mb-3" %>
  </div>
</div>

app/views/templates/_template.html.erb
<div class="container">
  <% @templates.each do |template| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <h4><%= template.name %></h4>
          </div>
          <div class="card-body">
            <p class="card-text">For template info please click View</p>
            <%= link_to "View", template_path(template), class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <%= link_to "Delete", template_path(template), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete this template?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(template.created_at) %> ago,
            edited <%= time_ago_in_words(template.updated_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/templates/index.html.erb
<h1 class="text-center mt-4">Templates List</h1>
<%= render 'template' %>

app/views/templates/new.html.erb
<h1 class="text-center mt-4">Create a new template</h1>
<%= render 'form' %>

app/views/templates/show.html.erb
<div class="container d-flex flex-column mt-4">
  <h2 class="text-center mt-">
    <%= link_to "Back", templates_path, class: "me-5 btn btn-outline-secondary" %>
    <%= @template.name %>
    <%= link_to "DOWNLOAD PDF", template_path(@template, format: :pdf), target: :_blank, class: "ms-5 btn btn-outline-primary" %>
  </h2>
</div>

<%= render 'document' %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'layouts/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="input-group row mb-3">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="input-group row mb-3">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="input-group justify-content-center mb-3">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Signup for Mini Dealmaker</h1>
<%= render 'form' %>